spring:
  datasource:
    url: jdbc:mysql://192.168.2.130:3306/wenxun?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: act10000
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      filters: stat,wall
      connection-properties: true
      stat-view-servlet:
        login-username: admin
        login-password: 123
      use-global-data-source-stat: true
      web-stat-filter:
        exclusions:
          -*.js
          -*.gif
          -*.jpg
          -*.png
          -*.css
          -*.ico
          -/druid/*

druid:
  stat:
    mergeSql: true
    slowSqlMillis: 500

mybatis:
  type-aliases-package: com.bhagava.traineemanage.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.bhagava.traineemanage: debug
